### ISSUE TITLE
SharkPCB update

### ISSUE THREAD

**Issue by Gondolindrim** [BenRoe/awesome-mechanical-keyboard#22]
Yo Ben!

Just passing to say that the SharkPCB repo now has plate and case files. A firmware is being built.

I'm saying this because the SharkPCB is listed as a pcb-only resource.

Thanks for your help!

**Comment by BenRoe** [comment]
Thank you for the information. I updated the SharkPCB.
Btw the image in you readme.md is broken.

**Comment by Gondolindrim** [comment]
Yeah just saw it. Will fix. Thanks
