### ISSUE TITLE
Add link to split keyboard comparison tool

### ISSUE THREAD

**Issue by jhelvy** [BenRoe/awesome-mechanical-keyboard#48]
Hi,

I built this [tool](https://jhelvy.shinyapps.io/splitkbcompare/) for comparing different split keyboard layouts (source code [here](https://github.com/jhelvy/splitKbCompare)). I figured this would be a good place to include a link to it. I wasn't sure where to put it though, so I'm just mentioning it here.

Cheers,
John

**Comment by BenRoe** [comment]
Great. Will add it to the tools section with the next commit.
