### ISSUE TITLE
Add Ergomac

### ISSUE THREAD

**Issue by LouWii** [BenRoe/awesome-mechanical-keyboard#8]
Hi

This post on reddit has come up recently https://www.reddit.com/r/MechanicalKeyboards/comments/9v682m/what_do_you_think_of_my_custom_split_ergo/

And there's a repo for the PCB files: https://github.com/LilBigMacky/ergomac

I can eventually make a pull request if you think we can add it to the list.

**Comment by BenRoe** [comment]
Hi,
yes do a PR.

**Comment by LouWii** [comment]
PR opened: https://github.com/BenRoe/awesome-mechanical-keyboard/pull/11
