### ISSUE TITLE
Build Guide Video section

### ISSUE THREAD

**Issue by BenRoe** [BenRoe/awesome-mechanical-keyboard#83]
Hi @rafaeldelboni,
The videos are great. Simple and useful. 
Create a new section on the [Tutorial site](https://github.com/BenRoe/awesome-mechanical-keyboard/blob/master/docs/tutorials.md) called Build-Videos, Build-Guide Videos, or Build-Log Videos?
What do you think fit's better.

**Comment by rafaeldelboni** [comment]
Thanks a lot @BenRoe! Hope the videos/buildlogs help someone.
